"""
roll_forward_instances.py
─────────────────────────────────────────────────────────────────────────────
Run this ONCE PER DAY (e.g. via cron at midnight).

For every active RouteSchedule (is_deleted = 0):
  - Find the latest (max) flight_date among its active FlightInstance rows.
  - Create exactly one new instance for (latest_date + 1 day), copying the
    schedule's current departure/arrival time and prices as the base values.

Example:
  If a schedule's latest active instance is dated 31/08/2026, this script
  will create a new instance dated 01/09/2026, keeping the "30 days ahead"
  rolling window intact as each day passes.

Schedules with zero active instances are skipped (they should already have
30 days generated by generate_30_days_instances() at creation time).
"""

from batch_common import get_session, models, DATE_FMT, timedelta, datetime, log


def extend_schedule_by_one_day(db, schedule) -> bool:
    """
    Adds one new FlightInstance for the given schedule, dated one day after
    its current latest active instance.
    Returns True if a new instance was created, False otherwise.
    """
    active_instances = db.query(models.FlightInstance).filter(
        models.FlightInstance.schedule_id == schedule.schedule_id,
        models.FlightInstance.is_deleted == 0
    ).all()

    if not active_instances:
        log(f"  [skip] schedule_id={schedule.schedule_id} -> no active instances found")
        return False

    # Parse flight_date strings and find the latest one
    try:
        max_date_obj = max(
            datetime.strptime(inst.flight_date.strip(), DATE_FMT)
            for inst in active_instances
        )
    except ValueError as e:
        log(f"  [error] schedule_id={schedule.schedule_id} -> invalid flight_date format: {e}")
        return False

    new_date_obj = max_date_obj + timedelta(days=1)
    new_date_str = new_date_obj.strftime(DATE_FMT)

    # Safety check: avoid creating a duplicate instance for the same date
    already_exists = db.query(models.FlightInstance).filter(
        models.FlightInstance.schedule_id == schedule.schedule_id,
        models.FlightInstance.flight_date == new_date_str,
        models.FlightInstance.is_deleted == 0
    ).first()

    if already_exists:
        log(f"  [skip] schedule_id={schedule.schedule_id} -> instance for {new_date_str} already exists")
        return False

    new_instance = models.FlightInstance(
        schedule_id=schedule.schedule_id,
        flight_date=new_date_str,
        economy_seats_occupied=0,
        business_seats_occupied=0,
        base_departure_time=schedule.departure_time.strip(),
        base_arrival_time=schedule.arrival_time.strip(),
        base_economy_price=schedule.economy_price,
        base_business_price=schedule.business_price,
        override_economy_price=None,
        override_business_price=None,
        status="SCHEDULED",
        is_deleted=0
    )
    db.add(new_instance)
    log(f"  [ok] schedule_id={schedule.schedule_id} -> created new instance for {new_date_str}")
    return True


def main():
    log("Roll-forward batch started")
    db = get_session()
    try:
        active_schedules = db.query(models.RouteSchedule).filter(
            models.RouteSchedule.is_deleted == 0
        ).all()

        created_count = 0
        for schedule in active_schedules:
            if extend_schedule_by_one_day(db, schedule):
                created_count += 1

        db.commit()
        log(f"Done. Schedules processed: {len(active_schedules)}, new instances created: {created_count}")

    except Exception as e:
        db.rollback()
        log(f"[FATAL ERROR] Roll-forward batch failed, rolled back. Reason: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    main()